export const Categories = {
    eatdrink: "eat-drink",
    fooddrink: "food-drink",
    restaurant: "restaurant",
    coffeetea: "coffee-tea",
    snacksfastfood: "snacks-fastfood",
    goingout: "going-out",
    sightsmuseums: "sights-museums",
    transport: "transport",
    accommodation: "accommodation",
    shopping: "shopping",
    leisureoutdoor: "leisure-outdoor",
    administrativeareasbuildings: "administrative-areas-buildings",
    naturalgeographical: "natural-geographical",
    petrolstation: "petrol-station",
    atmbankexchange: "atm-bank-exchange",
    toiletrestarea: "toilet-rest-area",
    hospitalhealthcarefacility: "hospital-health-care-facility",
}