export const Categories = {
    eatdrink: "restaurant",
    fooddrink: "restaurant",
    restaurant: "restaurant",
    coffeetea: "cafe",
    snacksfastfood: "pizza",
    goingout: "wine",
    sightsmuseums: "eye",
    transport: "bus",
    airport: "airplane",
    accommodation: "bed",
    shopping: "pricetags",
    leisureoutdoor: "bicycle",
    administrativeareasbuildings: "book",
    naturalgeographical: "leaf",
    petrolstation: "car",
    atmbankexchange: "cash",
    toiletrestarea: "map",
    hospitalhealthcarefacility: "heart",
}